# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/rzh/.conda/envs/kt-kernel/bin/cmake

# The command to remove a file.
RM = /home/rzh/.conda/envs/kt-kernel/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rzh/Projects/ktransformers/kt-kernel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rzh/Projects/ktransformers

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/rzh/.conda/envs/kt-kernel/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/rzh/.conda/envs/kt-kernel/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/rzh/.conda/envs/kt-kernel/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/rzh/.conda/envs/kt-kernel/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/rzh/.conda/envs/kt-kernel/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/rzh/.conda/envs/kt-kernel/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/rzh/.conda/envs/kt-kernel/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/rzh/.conda/envs/kt-kernel/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rzh/Projects/ktransformers/CMakeFiles /home/rzh/Projects/ktransformers//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rzh/Projects/ktransformers/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named llamafile

# Build rule for target.
llamafile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llamafile
.PHONY : llamafile

# fast build rule for target.
llamafile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/build
.PHONY : llamafile/fast

#=============================================================================
# Target rules for targets named kt_kernel_ext

# Build rule for target.
kt_kernel_ext: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kt_kernel_ext
.PHONY : kt_kernel_ext

# fast build rule for target.
kt_kernel_ext/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/build
.PHONY : kt_kernel_ext/fast

#=============================================================================
# Target rules for targets named ggml

# Build rule for target.
ggml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml
.PHONY : ggml

# fast build rule for target.
ggml/fast:
	$(MAKE) $(MAKESILENT) -f /home/rzh/Projects/ktransformers/third_party/llama.cpp/CMakeFiles/ggml.dir/build.make /home/rzh/Projects/ktransformers/third_party/llama.cpp/CMakeFiles/ggml.dir/build
.PHONY : ggml/fast

#=============================================================================
# Target rules for targets named ggml_static

# Build rule for target.
ggml_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml_static
.PHONY : ggml_static

# fast build rule for target.
ggml_static/fast:
	$(MAKE) $(MAKESILENT) -f /home/rzh/Projects/ktransformers/third_party/llama.cpp/CMakeFiles/ggml_static.dir/build.make /home/rzh/Projects/ktransformers/third_party/llama.cpp/CMakeFiles/ggml_static.dir/build
.PHONY : ggml_static/fast

#=============================================================================
# Target rules for targets named llama

# Build rule for target.
llama: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llama
.PHONY : llama

# fast build rule for target.
llama/fast:
	$(MAKE) $(MAKESILENT) -f /home/rzh/Projects/ktransformers/third_party/llama.cpp/CMakeFiles/llama.dir/build.make /home/rzh/Projects/ktransformers/third_party/llama.cpp/CMakeFiles/llama.dir/build
.PHONY : llama/fast

#=============================================================================
# Target rules for targets named build_info

# Build rule for target.
build_info: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_info
.PHONY : build_info

# fast build rule for target.
build_info/fast:
	$(MAKE) $(MAKESILENT) -f /home/rzh/Projects/ktransformers/third_party/llama.cpp/common/CMakeFiles/build_info.dir/build.make /home/rzh/Projects/ktransformers/third_party/llama.cpp/common/CMakeFiles/build_info.dir/build
.PHONY : build_info/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f /home/rzh/Projects/ktransformers/third_party/llama.cpp/common/CMakeFiles/common.dir/build.make /home/rzh/Projects/ktransformers/third_party/llama.cpp/common/CMakeFiles/common.dir/build
.PHONY : common/fast

cpu_backend/shared_mem_buffer.o: cpu_backend/shared_mem_buffer.cpp.o
.PHONY : cpu_backend/shared_mem_buffer.o

# target to build an object file
cpu_backend/shared_mem_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/cpu_backend/shared_mem_buffer.cpp.o
.PHONY : cpu_backend/shared_mem_buffer.cpp.o

cpu_backend/shared_mem_buffer.i: cpu_backend/shared_mem_buffer.cpp.i
.PHONY : cpu_backend/shared_mem_buffer.i

# target to preprocess a source file
cpu_backend/shared_mem_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/cpu_backend/shared_mem_buffer.cpp.i
.PHONY : cpu_backend/shared_mem_buffer.cpp.i

cpu_backend/shared_mem_buffer.s: cpu_backend/shared_mem_buffer.cpp.s
.PHONY : cpu_backend/shared_mem_buffer.s

# target to generate assembly for a file
cpu_backend/shared_mem_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/cpu_backend/shared_mem_buffer.cpp.s
.PHONY : cpu_backend/shared_mem_buffer.cpp.s

cpu_backend/task_queue.o: cpu_backend/task_queue.cpp.o
.PHONY : cpu_backend/task_queue.o

# target to build an object file
cpu_backend/task_queue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/cpu_backend/task_queue.cpp.o
.PHONY : cpu_backend/task_queue.cpp.o

cpu_backend/task_queue.i: cpu_backend/task_queue.cpp.i
.PHONY : cpu_backend/task_queue.i

# target to preprocess a source file
cpu_backend/task_queue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/cpu_backend/task_queue.cpp.i
.PHONY : cpu_backend/task_queue.cpp.i

cpu_backend/task_queue.s: cpu_backend/task_queue.cpp.s
.PHONY : cpu_backend/task_queue.s

# target to generate assembly for a file
cpu_backend/task_queue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/cpu_backend/task_queue.cpp.s
.PHONY : cpu_backend/task_queue.cpp.s

cpu_backend/worker_pool.o: cpu_backend/worker_pool.cpp.o
.PHONY : cpu_backend/worker_pool.o

# target to build an object file
cpu_backend/worker_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/cpu_backend/worker_pool.cpp.o
.PHONY : cpu_backend/worker_pool.cpp.o

cpu_backend/worker_pool.i: cpu_backend/worker_pool.cpp.i
.PHONY : cpu_backend/worker_pool.i

# target to preprocess a source file
cpu_backend/worker_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/cpu_backend/worker_pool.cpp.i
.PHONY : cpu_backend/worker_pool.cpp.i

cpu_backend/worker_pool.s: cpu_backend/worker_pool.cpp.s
.PHONY : cpu_backend/worker_pool.s

# target to generate assembly for a file
cpu_backend/worker_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/cpu_backend/worker_pool.cpp.s
.PHONY : cpu_backend/worker_pool.cpp.s

ext_bindings.o: ext_bindings.cpp.o
.PHONY : ext_bindings.o

# target to build an object file
ext_bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/ext_bindings.cpp.o
.PHONY : ext_bindings.cpp.o

ext_bindings.i: ext_bindings.cpp.i
.PHONY : ext_bindings.i

# target to preprocess a source file
ext_bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/ext_bindings.cpp.i
.PHONY : ext_bindings.cpp.i

ext_bindings.s: ext_bindings.cpp.s
.PHONY : ext_bindings.s

# target to generate assembly for a file
ext_bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/ext_bindings.cpp.s
.PHONY : ext_bindings.cpp.s

operators/kvcache/kvcache_attn.o: operators/kvcache/kvcache_attn.cpp.o
.PHONY : operators/kvcache/kvcache_attn.o

# target to build an object file
operators/kvcache/kvcache_attn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/kvcache/kvcache_attn.cpp.o
.PHONY : operators/kvcache/kvcache_attn.cpp.o

operators/kvcache/kvcache_attn.i: operators/kvcache/kvcache_attn.cpp.i
.PHONY : operators/kvcache/kvcache_attn.i

# target to preprocess a source file
operators/kvcache/kvcache_attn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/kvcache/kvcache_attn.cpp.i
.PHONY : operators/kvcache/kvcache_attn.cpp.i

operators/kvcache/kvcache_attn.s: operators/kvcache/kvcache_attn.cpp.s
.PHONY : operators/kvcache/kvcache_attn.s

# target to generate assembly for a file
operators/kvcache/kvcache_attn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/kvcache/kvcache_attn.cpp.s
.PHONY : operators/kvcache/kvcache_attn.cpp.s

operators/kvcache/kvcache_load_dump.o: operators/kvcache/kvcache_load_dump.cpp.o
.PHONY : operators/kvcache/kvcache_load_dump.o

# target to build an object file
operators/kvcache/kvcache_load_dump.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/kvcache/kvcache_load_dump.cpp.o
.PHONY : operators/kvcache/kvcache_load_dump.cpp.o

operators/kvcache/kvcache_load_dump.i: operators/kvcache/kvcache_load_dump.cpp.i
.PHONY : operators/kvcache/kvcache_load_dump.i

# target to preprocess a source file
operators/kvcache/kvcache_load_dump.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/kvcache/kvcache_load_dump.cpp.i
.PHONY : operators/kvcache/kvcache_load_dump.cpp.i

operators/kvcache/kvcache_load_dump.s: operators/kvcache/kvcache_load_dump.cpp.s
.PHONY : operators/kvcache/kvcache_load_dump.s

# target to generate assembly for a file
operators/kvcache/kvcache_load_dump.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/kvcache/kvcache_load_dump.cpp.s
.PHONY : operators/kvcache/kvcache_load_dump.cpp.s

operators/kvcache/kvcache_read_write.o: operators/kvcache/kvcache_read_write.cpp.o
.PHONY : operators/kvcache/kvcache_read_write.o

# target to build an object file
operators/kvcache/kvcache_read_write.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/kvcache/kvcache_read_write.cpp.o
.PHONY : operators/kvcache/kvcache_read_write.cpp.o

operators/kvcache/kvcache_read_write.i: operators/kvcache/kvcache_read_write.cpp.i
.PHONY : operators/kvcache/kvcache_read_write.i

# target to preprocess a source file
operators/kvcache/kvcache_read_write.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/kvcache/kvcache_read_write.cpp.i
.PHONY : operators/kvcache/kvcache_read_write.cpp.i

operators/kvcache/kvcache_read_write.s: operators/kvcache/kvcache_read_write.cpp.s
.PHONY : operators/kvcache/kvcache_read_write.s

# target to generate assembly for a file
operators/kvcache/kvcache_read_write.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/kvcache/kvcache_read_write.cpp.s
.PHONY : operators/kvcache/kvcache_read_write.cpp.s

operators/kvcache/kvcache_utils.o: operators/kvcache/kvcache_utils.cpp.o
.PHONY : operators/kvcache/kvcache_utils.o

# target to build an object file
operators/kvcache/kvcache_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/kvcache/kvcache_utils.cpp.o
.PHONY : operators/kvcache/kvcache_utils.cpp.o

operators/kvcache/kvcache_utils.i: operators/kvcache/kvcache_utils.cpp.i
.PHONY : operators/kvcache/kvcache_utils.i

# target to preprocess a source file
operators/kvcache/kvcache_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/kvcache/kvcache_utils.cpp.i
.PHONY : operators/kvcache/kvcache_utils.cpp.i

operators/kvcache/kvcache_utils.s: operators/kvcache/kvcache_utils.cpp.s
.PHONY : operators/kvcache/kvcache_utils.s

# target to generate assembly for a file
operators/kvcache/kvcache_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/kvcache/kvcache_utils.cpp.s
.PHONY : operators/kvcache/kvcache_utils.cpp.s

operators/llamafile/linear.o: operators/llamafile/linear.cpp.o
.PHONY : operators/llamafile/linear.o

# target to build an object file
operators/llamafile/linear.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/llamafile/linear.cpp.o
.PHONY : operators/llamafile/linear.cpp.o

operators/llamafile/linear.i: operators/llamafile/linear.cpp.i
.PHONY : operators/llamafile/linear.i

# target to preprocess a source file
operators/llamafile/linear.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/llamafile/linear.cpp.i
.PHONY : operators/llamafile/linear.cpp.i

operators/llamafile/linear.s: operators/llamafile/linear.cpp.s
.PHONY : operators/llamafile/linear.s

# target to generate assembly for a file
operators/llamafile/linear.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/llamafile/linear.cpp.s
.PHONY : operators/llamafile/linear.cpp.s

operators/llamafile/mlp.o: operators/llamafile/mlp.cpp.o
.PHONY : operators/llamafile/mlp.o

# target to build an object file
operators/llamafile/mlp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/llamafile/mlp.cpp.o
.PHONY : operators/llamafile/mlp.cpp.o

operators/llamafile/mlp.i: operators/llamafile/mlp.cpp.i
.PHONY : operators/llamafile/mlp.i

# target to preprocess a source file
operators/llamafile/mlp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/llamafile/mlp.cpp.i
.PHONY : operators/llamafile/mlp.cpp.i

operators/llamafile/mlp.s: operators/llamafile/mlp.cpp.s
.PHONY : operators/llamafile/mlp.s

# target to generate assembly for a file
operators/llamafile/mlp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/operators/llamafile/mlp.cpp.s
.PHONY : operators/llamafile/mlp.cpp.s

third_party/llamafile/flags.o: third_party/llamafile/flags.cpp.o
.PHONY : third_party/llamafile/flags.o

# target to build an object file
third_party/llamafile/flags.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/flags.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/flags.cpp.o
.PHONY : third_party/llamafile/flags.cpp.o

third_party/llamafile/flags.i: third_party/llamafile/flags.cpp.i
.PHONY : third_party/llamafile/flags.i

# target to preprocess a source file
third_party/llamafile/flags.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/flags.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/flags.cpp.i
.PHONY : third_party/llamafile/flags.cpp.i

third_party/llamafile/flags.s: third_party/llamafile/flags.cpp.s
.PHONY : third_party/llamafile/flags.s

# target to generate assembly for a file
third_party/llamafile/flags.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/flags.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/flags.cpp.s
.PHONY : third_party/llamafile/flags.cpp.s

third_party/llamafile/iqk_mul_mat_amd_avx2.o: third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.o
.PHONY : third_party/llamafile/iqk_mul_mat_amd_avx2.o

# target to build an object file
third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.o
.PHONY : third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.o

third_party/llamafile/iqk_mul_mat_amd_avx2.i: third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.i
.PHONY : third_party/llamafile/iqk_mul_mat_amd_avx2.i

# target to preprocess a source file
third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.i
.PHONY : third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.i

third_party/llamafile/iqk_mul_mat_amd_avx2.s: third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.s
.PHONY : third_party/llamafile/iqk_mul_mat_amd_avx2.s

# target to generate assembly for a file
third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.s
.PHONY : third_party/llamafile/iqk_mul_mat_amd_avx2.cpp.s

third_party/llamafile/iqk_mul_mat_amd_zen4.o: third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.o
.PHONY : third_party/llamafile/iqk_mul_mat_amd_zen4.o

# target to build an object file
third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.o
.PHONY : third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.o

third_party/llamafile/iqk_mul_mat_amd_zen4.i: third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.i
.PHONY : third_party/llamafile/iqk_mul_mat_amd_zen4.i

# target to preprocess a source file
third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.i
.PHONY : third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.i

third_party/llamafile/iqk_mul_mat_amd_zen4.s: third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.s
.PHONY : third_party/llamafile/iqk_mul_mat_amd_zen4.s

# target to generate assembly for a file
third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.s
.PHONY : third_party/llamafile/iqk_mul_mat_amd_zen4.cpp.s

third_party/llamafile/iqk_mul_mat_arm82.o: third_party/llamafile/iqk_mul_mat_arm82.cpp.o
.PHONY : third_party/llamafile/iqk_mul_mat_arm82.o

# target to build an object file
third_party/llamafile/iqk_mul_mat_arm82.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/iqk_mul_mat_arm82.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/iqk_mul_mat_arm82.cpp.o
.PHONY : third_party/llamafile/iqk_mul_mat_arm82.cpp.o

third_party/llamafile/iqk_mul_mat_arm82.i: third_party/llamafile/iqk_mul_mat_arm82.cpp.i
.PHONY : third_party/llamafile/iqk_mul_mat_arm82.i

# target to preprocess a source file
third_party/llamafile/iqk_mul_mat_arm82.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/iqk_mul_mat_arm82.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/iqk_mul_mat_arm82.cpp.i
.PHONY : third_party/llamafile/iqk_mul_mat_arm82.cpp.i

third_party/llamafile/iqk_mul_mat_arm82.s: third_party/llamafile/iqk_mul_mat_arm82.cpp.s
.PHONY : third_party/llamafile/iqk_mul_mat_arm82.s

# target to generate assembly for a file
third_party/llamafile/iqk_mul_mat_arm82.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/iqk_mul_mat_arm82.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/iqk_mul_mat_arm82.cpp.s
.PHONY : third_party/llamafile/iqk_mul_mat_arm82.cpp.s

third_party/llamafile/sgemm.o: third_party/llamafile/sgemm.cpp.o
.PHONY : third_party/llamafile/sgemm.o

# target to build an object file
third_party/llamafile/sgemm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/sgemm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/sgemm.cpp.o
.PHONY : third_party/llamafile/sgemm.cpp.o

third_party/llamafile/sgemm.i: third_party/llamafile/sgemm.cpp.i
.PHONY : third_party/llamafile/sgemm.i

# target to preprocess a source file
third_party/llamafile/sgemm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/sgemm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/sgemm.cpp.i
.PHONY : third_party/llamafile/sgemm.cpp.i

third_party/llamafile/sgemm.s: third_party/llamafile/sgemm.cpp.s
.PHONY : third_party/llamafile/sgemm.s

# target to generate assembly for a file
third_party/llamafile/sgemm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/sgemm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/sgemm.cpp.s
.PHONY : third_party/llamafile/sgemm.cpp.s

third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.o: third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.o

third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.i: third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.i

third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.s: third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.cpp.s

third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.o: third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.o

third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.i: third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.i

third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.s: third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.cpp.s

third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.o: third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.o

third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.i: third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.i

third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.s: third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.cpp.s

third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.o: third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.o

third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.i: third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.i

third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.s: third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.cpp.s

third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.o: third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.o

third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.i: third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.i

third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.s: third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.cpp.s

third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.o: third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.o

third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.i: third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.i

third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.s: third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.cpp.s

third_party/llamafile/tinyblas_cpu_mixmul_arm80.o: third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_arm80.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.o

third_party/llamafile/tinyblas_cpu_mixmul_arm80.i: third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_arm80.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.i

third_party/llamafile/tinyblas_cpu_mixmul_arm80.s: third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_arm80.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_arm80.cpp.s

third_party/llamafile/tinyblas_cpu_mixmul_arm82.o: third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_arm82.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.o

third_party/llamafile/tinyblas_cpu_mixmul_arm82.i: third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_arm82.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.i

third_party/llamafile/tinyblas_cpu_mixmul_arm82.s: third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_arm82.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_mixmul_arm82.cpp.s

third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.o: third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.o

third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.i: third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.i

third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.s: third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.cpp.s

third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.o: third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.o

third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.i: third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.i

third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.s: third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.cpp.s

third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.o: third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.o

third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.i: third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.i

third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.s: third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.cpp.s

third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.o: third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.o

third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.i: third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.i

third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.s: third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.cpp.s

third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.o: third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.o

third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.i: third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.i

third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.s: third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.cpp.s

third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.o: third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.o

third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.i: third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.i

third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.s: third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.cpp.s

third_party/llamafile/tinyblas_cpu_sgemm_arm80.o: third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_arm80.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.o

third_party/llamafile/tinyblas_cpu_sgemm_arm80.i: third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_arm80.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.i

third_party/llamafile/tinyblas_cpu_sgemm_arm80.s: third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_arm80.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_arm80.cpp.s

third_party/llamafile/tinyblas_cpu_sgemm_arm82.o: third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_arm82.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.o

third_party/llamafile/tinyblas_cpu_sgemm_arm82.i: third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_arm82.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.i

third_party/llamafile/tinyblas_cpu_sgemm_arm82.s: third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_arm82.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_sgemm_arm82.cpp.s

third_party/llamafile/tinyblas_cpu_unsupported.o: third_party/llamafile/tinyblas_cpu_unsupported.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_unsupported.o

# target to build an object file
third_party/llamafile/tinyblas_cpu_unsupported.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_unsupported.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_unsupported.cpp.o
.PHONY : third_party/llamafile/tinyblas_cpu_unsupported.cpp.o

third_party/llamafile/tinyblas_cpu_unsupported.i: third_party/llamafile/tinyblas_cpu_unsupported.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_unsupported.i

# target to preprocess a source file
third_party/llamafile/tinyblas_cpu_unsupported.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_unsupported.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_unsupported.cpp.i
.PHONY : third_party/llamafile/tinyblas_cpu_unsupported.cpp.i

third_party/llamafile/tinyblas_cpu_unsupported.s: third_party/llamafile/tinyblas_cpu_unsupported.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_unsupported.s

# target to generate assembly for a file
third_party/llamafile/tinyblas_cpu_unsupported.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llamafile.dir/build.make CMakeFiles/llamafile.dir/third_party/llamafile/tinyblas_cpu_unsupported.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kt_kernel_ext.dir/build.make CMakeFiles/kt_kernel_ext.dir/third_party/llamafile/tinyblas_cpu_unsupported.cpp.s
.PHONY : third_party/llamafile/tinyblas_cpu_unsupported.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... build_info"
	@echo "... common"
	@echo "... ggml"
	@echo "... ggml_static"
	@echo "... kt_kernel_ext"
	@echo "... llama"
	@echo "... llamafile"
	@echo "... cpu_backend/shared_mem_buffer.o"
	@echo "... cpu_backend/shared_mem_buffer.i"
	@echo "... cpu_backend/shared_mem_buffer.s"
	@echo "... cpu_backend/task_queue.o"
	@echo "... cpu_backend/task_queue.i"
	@echo "... cpu_backend/task_queue.s"
	@echo "... cpu_backend/worker_pool.o"
	@echo "... cpu_backend/worker_pool.i"
	@echo "... cpu_backend/worker_pool.s"
	@echo "... ext_bindings.o"
	@echo "... ext_bindings.i"
	@echo "... ext_bindings.s"
	@echo "... operators/kvcache/kvcache_attn.o"
	@echo "... operators/kvcache/kvcache_attn.i"
	@echo "... operators/kvcache/kvcache_attn.s"
	@echo "... operators/kvcache/kvcache_load_dump.o"
	@echo "... operators/kvcache/kvcache_load_dump.i"
	@echo "... operators/kvcache/kvcache_load_dump.s"
	@echo "... operators/kvcache/kvcache_read_write.o"
	@echo "... operators/kvcache/kvcache_read_write.i"
	@echo "... operators/kvcache/kvcache_read_write.s"
	@echo "... operators/kvcache/kvcache_utils.o"
	@echo "... operators/kvcache/kvcache_utils.i"
	@echo "... operators/kvcache/kvcache_utils.s"
	@echo "... operators/llamafile/linear.o"
	@echo "... operators/llamafile/linear.i"
	@echo "... operators/llamafile/linear.s"
	@echo "... operators/llamafile/mlp.o"
	@echo "... operators/llamafile/mlp.i"
	@echo "... operators/llamafile/mlp.s"
	@echo "... third_party/llamafile/flags.o"
	@echo "... third_party/llamafile/flags.i"
	@echo "... third_party/llamafile/flags.s"
	@echo "... third_party/llamafile/iqk_mul_mat_amd_avx2.o"
	@echo "... third_party/llamafile/iqk_mul_mat_amd_avx2.i"
	@echo "... third_party/llamafile/iqk_mul_mat_amd_avx2.s"
	@echo "... third_party/llamafile/iqk_mul_mat_amd_zen4.o"
	@echo "... third_party/llamafile/iqk_mul_mat_amd_zen4.i"
	@echo "... third_party/llamafile/iqk_mul_mat_amd_zen4.s"
	@echo "... third_party/llamafile/iqk_mul_mat_arm82.o"
	@echo "... third_party/llamafile/iqk_mul_mat_arm82.i"
	@echo "... third_party/llamafile/iqk_mul_mat_arm82.s"
	@echo "... third_party/llamafile/sgemm.o"
	@echo "... third_party/llamafile/sgemm.i"
	@echo "... third_party/llamafile/sgemm.s"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.o"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.i"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_avx.s"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.o"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.i"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_avx2.s"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.o"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.i"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_avx512f.s"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.o"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.i"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_avxvnni.s"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.o"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.i"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_fma.s"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.o"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.i"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_amd_zen4.s"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_arm80.o"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_arm80.i"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_arm80.s"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_arm82.o"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_arm82.i"
	@echo "... third_party/llamafile/tinyblas_cpu_mixmul_arm82.s"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.o"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.i"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_avx.s"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.o"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.i"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_avx2.s"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.o"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.i"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_avx512f.s"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.o"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.i"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_avxvnni.s"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.o"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.i"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_fma.s"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.o"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.i"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_amd_zen4.s"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_arm80.o"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_arm80.i"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_arm80.s"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_arm82.o"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_arm82.i"
	@echo "... third_party/llamafile/tinyblas_cpu_sgemm_arm82.s"
	@echo "... third_party/llamafile/tinyblas_cpu_unsupported.o"
	@echo "... third_party/llamafile/tinyblas_cpu_unsupported.i"
	@echo "... third_party/llamafile/tinyblas_cpu_unsupported.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

