name: "\U0001F41B Bug / Help"
description: Create a report to help us improve the ktransformers project
labels: ["pending"]
body:
  - type: markdown
    attributes:
      value: |
        Issues included in **[FAQs](https://github.com/kvcache-ai/ktransformers/issues/1608)** or those with **insufficient** information may be closed without a response.
        已经包含在 **[常见问题](https://github.com/kvcache-ai/ktransformers/issues/1608)** 内或提供信息**不完整**的 issues 可能不会被回复。

  - type: checkboxes
    id: reminder
    attributes:
      label: Reminder
      description: |
        Please ensure you have read the above rules carefully and searched the existing issues (including FAQs).
        请确保您已经认真阅读了上述规则并且搜索过现有的 issues（包括常见问题）。

      options:
        - label: I have read the above rules and searched the existing issues.
          required: true

  - type: textarea
    id: system-info
    validations:
      required: true
    attributes:
      label: System Info
      description: |
        Please share your system info with us. You can run the command **lscpu**, ** nvidia-smi ** etc. and copy-paste its output below.
        请提供您的系统信息。您可以在命令行运行 **lscpu**, **nvidia-smi** 等命令，并将其输出复制到该文本框中。

      placeholder: ktransformers version,sglang version, platform, python version, cpu info, GPU/NPU info ...

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please provide entry arguments, error messages and stack traces that reproduces the problem.
        请提供入口参数，错误日志以及异常堆栈以便于我们复现问题。

      value: |
        ```text
        Put your message here.
        ```

  - type: textarea
    id: others
    validations:
      required: false
    attributes:
      label: Others