name: 🚀 新功能请求
description: 为项目提出新功能建议
title: "[Feature] "

body:
- type: checkboxes
  attributes:
    label: 检查清单
    options:
    - label: 1. 如果您提出的不是新功能而是问题，请在讨论区发起讨论 https://github.com/kvcache-ai/ktransformers/discussions。否则该 issue 将被关闭
    - label: 2. 为方便社区交流，我将使用中文/英文或附上英文/中文翻译（如使用其他语言）。未附带翻译的非英文/中文内容可能会被关闭
- type: textarea
  attributes:
    label: 需求背景
    description: |
      清晰简洁地描述该功能的背景需求
  validations:
    required: true
- type: textarea
  attributes:
    label: 相关资源
    description: |
      如果有官方代码实现或第三方实现，请在此提供相关信息，这将非常有帮助