"""Small fixed model recipes, deliberately not a benchmark or quality gate."""

from pathlib import Path


def training_config(case, output):
    deepseek = case == "deepseek_v31_lora"
    return {
        "model_name_or_path": "/models/deepseek_v31" if deepseek else "/models/qwen3",
        "trust_remote_code": False,
        "flash_attn": "sdpa",
        "stage": "sft",
        "do_train": True,
        "do_eval": False,
        "finetuning_type": "lora",
        "lora_rank": 8,
        "lora_alpha": 16,
        "lora_dropout": 0.0,
        "lora_target": "all",
        "dataset": "kt_ci_smoke",
        "dataset_dir": "/work/data",
        "template": "deepseek3" if deepseek else "qwen3_nothink",
        "cutoff_len": 512,
        "packing": False,
        "preprocessing_num_workers": 1,
        "dataloader_num_workers": 0,
        "disable_shuffling": True,
        "logging_steps": 1,
        "logging_nan_inf_filter": False,
        "save_strategy": "no",
        "plot_loss": False,
        "report_to": "none",
        "overwrite_output_dir": False,
        "output_dir": str(Path(output) / "trainer"),
        "per_device_train_batch_size": 1,
        "gradient_accumulation_steps": 1,
        "learning_rate": 1e-4,
        "lr_scheduler_type": "constant",
        "warmup_steps": 0,
        "optim": "adamw_torch_fused",
        "max_steps": 1,
        "bf16": True,
        "pure_bf16": False,
        "seed": 42,
        "data_seed": 42,
        "ddp_timeout": 1800,
        "use_kt": True,
        "kt_cpu_activation": "retain",
        "kt_config": {
            "kt_expert_weight_format": "fp8" if deepseek else "bf16",
            "kt_backend": "auto",
            "kt_num_threads": 64,
            "kt_tp_enabled": True,
            "kt_threadpool_count": 2,
            "kt_max_cache_depth": 2,
            "kt_share_backward_bb": True,
            "kt_num_gpu_experts": 0,
            "kt_force_fused_expert_lora": True,
            "kt_model_max_length": 640,
        },
    }


def accelerate_config(world_size):
    return {
        "compute_environment": "LOCAL_MACHINE",
        "distributed_type": "FSDP",
        "num_machines": 1,
        "num_processes": world_size,
        "mixed_precision": "bf16",
        "rdzv_backend": "static",
        "same_network": True,
        "use_cpu": False,
        "fsdp_config": {
            "fsdp_auto_wrap_policy": "TRANSFORMER_BASED_WRAP",
            "fsdp_cpu_ram_efficient_loading": True,
            "fsdp_offload_params": False,
            "fsdp_reshard_after_forward": True,
            "fsdp_state_dict_type": "FULL_STATE_DICT",
            "fsdp_version": 2,
        },
    }


def glm_command(python):
    return [
        str(python),
        "-m",
        "sglang.launch_server",
        "--model-path",
        "/models/glm53",
        "--kt-weight-path",
        "/models/glm53",
        "--served-model-name",
        "GLM-5.3-Flash",
        "--host",
        "127.0.0.1",
        "--port",
        "30000",
        "--tp-size",
        "4",
        "--context-length",
        "8192",
        "--mem-fraction-static",
        "0.60",
        "--chunked-prefill-size",
        "4096",
        "--kt-method",
        "FP8",
        "--kt-cpuinfer",
        "64",
        "--kt-threadpool-count",
        "2",
        "--kt-num-gpu-experts",
        "0",
        "--kt-gpu-prefill-token-threshold",
        "2048",
        "--cuda-graph-bs",
        "1",
        "2",
        "4",
        "--tool-call-parser",
        "glm47",
        "--reasoning-parser",
        "glm45",
    ]
