#!/usr/bin/env python3
"""Replay expert-access traces against multiple residency policies."""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple


REPO_ROOT = Path(__file__).resolve().parents[1]
WEIGHT_PROVIDER_PATH = REPO_ROOT / "python" / "utils" / "weight_provider.py"

SPEC = importlib.util.spec_from_file_location("weight_provider", WEIGHT_PROVIDER_PATH)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError(f"Failed to load weight_provider from {WEIGHT_PROVIDER_PATH}")
weight_provider = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(weight_provider)

create_residency_policy = weight_provider.create_residency_policy
load_residency_policy_config = weight_provider.load_residency_policy_config


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Replay Tier0 expert-access traces against multiple policies.")
    parser.add_argument("--trace", type=Path, required=True, help="JSONL trace generated by KT_RESIDENCY_TRACE_PATH")
    parser.add_argument(
        "--policies",
        default="baseline,lru,2q,slru,sieve,s3fifo,w_tinylfu",
        help="Comma-separated policy names to compare",
    )
    parser.add_argument("--capacity", type=int, default=None, help="Pinned expert capacity override")
    parser.add_argument("--num-experts", type=int, default=None, help="Expert count override")
    parser.add_argument("--layer", default="all", help="Single layer index or 'all'")
    parser.add_argument(
        "--policy-config-json",
        default=None,
        help="Optional JSON config applied to every policy instance",
    )
    parser.add_argument("--output-json", type=Path, default=None, help="Write machine-readable summary to JSON")
    parser.add_argument("--output-csv", type=Path, default=None, help="Write summary rows to CSV")
    return parser.parse_args()


def load_trace(path: Path) -> List[Dict[str, Any]]:
    events: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for lineno, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on line {lineno} of {path}") from exc
            accesses = event.get("accesses")
            if accesses is None:
                accesses = event.get("expert_ids")
            if accesses is None:
                raise ValueError(f"Trace line {lineno} is missing 'accesses'")
            event["accesses"] = accesses
            event["layer_idx"] = int(event.get("layer_idx", 0))
            events.append(event)
    if not events:
        raise ValueError(f"No events found in trace {path}")
    return events


def infer_shape(events: Iterable[Dict[str, Any]]) -> Tuple[int, int]:
    capacity = 0
    num_experts = 0
    for event in events:
        capacity = max(capacity, int(event.get("capacity", 0)))
        for expert_id in event.get("accesses", []):
            try:
                num_experts = max(num_experts, int(expert_id) + 1)
            except (TypeError, ValueError):
                continue
        num_experts = max(num_experts, int(event.get("num_experts", 0)))
    return capacity, num_experts


def summarize_policy(policy: Any, layer_idx: int) -> Dict[str, Any]:
    snapshot = policy.snapshot()
    stats = snapshot["stats"]
    hits = float(stats["hits"])
    misses = float(stats["misses"])
    accesses = hits + misses
    return {
        "layer_idx": layer_idx,
        "policy": snapshot["policy"],
        "capacity": snapshot["capacity"],
        "accesses": int(accesses),
        "hits": int(hits),
        "misses": int(misses),
        "hit_rate": 0.0 if accesses <= 0 else hits / accesses,
        "promotions": int(stats["promotions"]),
        "demotions": int(stats["demotions"]),
        "prefetch_candidates": int(stats["prefetch_candidates"]),
        "final_resident_count": len(snapshot["resident"]),
        "final_resident": snapshot["resident"],
    }


def print_table(rows: List[Dict[str, Any]]) -> None:
    headers = [
        ("layer_idx", "layer"),
        ("policy", "policy"),
        ("accesses", "accesses"),
        ("hit_rate", "hit_rate"),
        ("promotions", "promote"),
        ("demotions", "demote"),
        ("prefetch_candidates", "prefetch"),
        ("final_resident_count", "resident"),
    ]
    widths = {}
    for key, label in headers:
        widths[key] = max(
            len(label), *(len(f"{row[key]:.4f}") if isinstance(row[key], float) else len(str(row[key])) for row in rows)
        )

    def fmt(key: str, value: Any) -> str:
        if isinstance(value, float):
            return f"{value:.4f}".rjust(widths[key])
        return str(value).rjust(widths[key])

    header = " ".join(label.rjust(widths[key]) for key, label in headers)
    print(header)
    print(" ".join("-" * widths[key] for key, _label in headers))
    for row in rows:
        print(" ".join(fmt(key, row[key]) for key, _label in headers))


def main() -> int:
    args = parse_args()
    events = load_trace(args.trace)
    capacity_from_trace, num_experts_from_trace = infer_shape(events)
    capacity = args.capacity if args.capacity is not None else capacity_from_trace
    num_experts = args.num_experts if args.num_experts is not None else num_experts_from_trace
    if capacity <= 0:
        raise ValueError("Pinned capacity is required; provide --capacity or include it in the trace")
    if num_experts <= 0:
        raise ValueError("Expert count is required; provide --num-experts or include it in the trace")

    layer_filter = None if args.layer == "all" else int(args.layer)
    policy_names = [name.strip() for name in args.policies.split(",") if name.strip()]
    policy_config = load_residency_policy_config(args.policy_config_json)

    grouped: Dict[int, List[Dict[str, Any]]] = {}
    for event in events:
        layer_idx = int(event["layer_idx"])
        if layer_filter is not None and layer_idx != layer_filter:
            continue
        grouped.setdefault(layer_idx, []).append(event)

    if not grouped:
        raise ValueError("No trace rows matched the requested layer filter")

    rows: List[Dict[str, Any]] = []
    for layer_idx, layer_events in sorted(grouped.items()):
        for policy_name in policy_names:
            policy = create_residency_policy(
                policy_name,
                num_experts=num_experts,
                capacity=capacity,
                config=policy_config,
            )
            for event in layer_events:
                policy.record_accesses(event["accesses"])
            rows.append(summarize_policy(policy, layer_idx))

    print_table(rows)

    if args.output_json is not None:
        args.output_json.parent.mkdir(parents=True, exist_ok=True)
        args.output_json.write_text(json.dumps(rows, indent=2, ensure_ascii=False), encoding="utf-8")

    if args.output_csv is not None:
        args.output_csv.parent.mkdir(parents=True, exist_ok=True)
        with args.output_csv.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(
                f,
                fieldnames=[
                    "layer_idx",
                    "policy",
                    "capacity",
                    "accesses",
                    "hits",
                    "misses",
                    "hit_rate",
                    "promotions",
                    "demotions",
                    "prefetch_candidates",
                    "final_resident_count",
                    "final_resident",
                ],
            )
            writer.writeheader()
            writer.writerows(rows)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
